### ISSUE TITLE
Use tools:text in layout

### ISSUE THREAD

**Issue by kirillsmirnov1** [kirillsmirnov1/Friends-reminder-android#16]
Instead of using android:text and string resources.

Also, remove all unused strings after that.

**Comment by KnightMode** [comment]
Working on it.

**Comment by KnightMode** [comment]
**PR link:** https://github.com/kirillsmirnov1/Friends-reminder-android/pull/25

**Comment by KnightMode** [comment]
Hi @kirillsmirnov1 
have raised a new PR: https://github.com/kirillsmirnov1/Friends-reminder-android/pull/34 as per your feedback.
