### ISSUE TITLE
«No data» notice

### ISSUE THREAD

**Issue by kirillsmirnov1** [kirillsmirnov1/Friends-reminder-android#21]
Show «you have no X» message, then there is no data to show in opened activity

**Comment by Rnkumar** [comment]
I have added a pull request which will add this enhancement in InteractionsFragment, LastInteractionsFragment and FriendsFragment. I have added the string for 'ru' lang as well. 

Kindly refer to the following pull request: #26

**Comment by Rnkumar** [comment]
Resolved with the changes mentioned in the previous pull request.
new link: https://github.com/kirillsmirnov1/Friends-reminder-android/pull/33
