### ISSUE TITLE
Scrollbar in activities with RecyclerView

### ISSUE THREAD

**Issue by kirillsmirnov1** [kirillsmirnov1/Friends-reminder-android#22]
Using fast scrolling, like [here](https://android.jlelse.eu/fast-scrolling-with-recyclerview-2b89d4574688)

**Comment by ramyakus** [comment]
Do we need to add scrollbars in recyclerview?

**Comment by ramyakus** [comment]
Raised MR.
 https://github.com/kirillsmirnov1/Friends-reminder-android/pull/24
